import { useState } from "react";
import { getNarrative } from "../api";

const RANK = { high: 0, medium: 1, low: 2 };

export default function AiNarrative({ datasetId }) {
  const [data, setData] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const generate = async () => {
    setBusy(true);
    setError(null);
    try {
      setData(await getNarrative(datasetId));
    } catch (e) {
      setError(e?.response?.data?.detail || "Could not generate narrative");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="ai-narrative">
      <div className="ai-narrative__head">
        <div className="ai-narrative__title">
          AI narrative &amp; recommendations
          <span className="ai-narrative__sub">executive brief + suggested actions</span>
        </div>
        <button className="ai-gen" onClick={generate} disabled={busy}>
          {busy ? "Generating…" : data ? "Regenerate" : "Generate"}
        </button>
      </div>

      {error && <div className="ai-error">{error}</div>}
      {!data && !busy && (
        <div className="ai-empty">
          Produce a plain-English brief and prioritized actions from your data. Uses your configured AI
          provider (Claude, OpenAI, Gemini, Ollama, …) or the built-in offline summary. Numbers are checked
          against the data — invented figures are flagged.
        </div>
      )}

      {data && (
        <>
          {data.headline && <div className="ai-headline">{data.headline}</div>}
          {data.narrative && <p className="ai-body">{data.narrative}</p>}
          {data.recommendations?.length > 0 && (
            <div className="ai-recs">
              {[...data.recommendations].sort((a, b) => RANK[a.priority] - RANK[b.priority]).map((r, i) => (
                <div className={`ai-rec ai-rec--${r.priority}`} key={i}>
                  <span className="ai-rec__pri">{r.priority}</span>
                  <div>
                    <div className="ai-rec__title">{r.title}</div>
                    <div className="ai-rec__detail">{r.detail}</div>
                  </div>
                </div>
              ))}
            </div>
          )}
          <div className="ai-foot">
            <span>Generated by {data.provider}{data.model ? ` · ${data.model}` : ""}</span>
            {data.unverified_numbers?.length > 0 && (
              <span className="ai-warn">⚠ {data.unverified_numbers.length} figure(s) not auto-verified against the data</span>
            )}
          </div>
        </>
      )}
    </div>
  );
}
