#!/usr/bin/env python3
"""Render the legal templates against docs/legal/company.json.

One source of facts, several documents. Change a company detail once and every
document follows, which is the usual way legal pages quietly become untrue.

    python scripts/build_legal.py           # render into docs/legal/build/
    python scripts/build_legal.py --dev     # render with obvious placeholders
    python scripts/build_legal.py --check   # exit non-zero if anything is unfilled

`--dev` exists so the pages can be linked, read and demoed during development
without a lawyer or real company details. It reads company.dev.json, stamps a
loud banner, and **can never satisfy `--check`** — placeholder values cannot
become a live policy by being left in place.

`--check` runs in the test suite, so a document still containing a TODO or an
unreplaced {{TOKEN}} cannot reach a website by accident.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEGAL = ROOT / "docs" / "legal"
TEMPLATES = LEGAL / "templates"
BUILD = LEGAL / "build"

TOKEN = re.compile(r"\{\{([A-Z0-9_]+)\}\}")

BANNER = """<!--
  GENERATED — do not edit this file.

  Source:   docs/legal/templates/{name}
  Values:   {values}
  Rebuild:  python scripts/build_legal.py{flag}

  DRAFT. Reviewed by counsel: NO. See docs/legal/README.md before publishing.
-->

"""

DEV_WARNING = """> **DEVELOPMENT BUILD — NOT A REAL POLICY.**
> Every company detail below is a placeholder. This document has no legal
> effect and must not be published. Fill `docs/legal/company.json` and have
> counsel review it before this becomes real.

"""


def load_values(dev: bool = False) -> dict[str, str]:
    source = LEGAL / ("company.dev.json" if dev else "company.json")
    raw = json.loads(source.read_text(encoding="utf-8"))
    return {k: v for k, v in raw.items() if not k.startswith("_")}


def render(text: str, values: dict[str, str]) -> tuple[str, set[str]]:
    """Substitute tokens; report any the values file does not define."""
    missing: set[str] = set()

    def swap(match: re.Match) -> str:
        key = match.group(1)
        if key not in values:
            missing.add(key)
            return match.group(0)
        return str(values[key])

    return TOKEN.sub(swap, text), missing


def unfilled(values: dict[str, str]) -> list[str]:
    return sorted(k for k, v in values.items() if str(v).strip().startswith("TODO"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify everything is filled in; write nothing")
    parser.add_argument("--dev", action="store_true",
                        help="render with obvious placeholders, for development only")
    args = parser.parse_args()

    # Development placeholders can never satisfy the publish gate. If they
    # could, "we'll fill it in later" would quietly become the live policy.
    if args.dev and args.check:
        print("--dev is never publishable; --check always fails for it "
              "by design. Fill company.json instead.", file=sys.stderr)
        return 1

    source = "docs/legal/company.dev.json" if args.dev else "docs/legal/company.json"
    values = load_values(dev=args.dev)
    templates = sorted(TEMPLATES.glob("*.md"))
    if not templates:
        print("no templates found", file=sys.stderr)
        return 1

    problems: list[str] = []
    todos = unfilled(values)
    if todos:
        problems.append(
            f"{source} still has placeholders:\n"
            + "\n".join(f"    {k}" for k in todos)
        )

    banner = BANNER.format(
        name="{name}",
        values=source + ("   ← PLACEHOLDERS, NOT REAL" if args.dev else ""),
        flag=" --dev" if args.dev else "",
    )

    rendered: dict[Path, str] = {}
    for template in templates:
        text = template.read_text(encoding="utf-8")
        out, missing = render(text, values)
        if missing:
            problems.append(
                f"{template.name} uses tokens {source} does not define: "
                + ", ".join(sorted(missing))
            )
        # a leftover TODO inside the prose itself
        for i, line in enumerate(out.split("\n"), 1):
            if "TODO" in line and not line.lstrip().startswith(">"):
                problems.append(f"{template.name}:{i} still says TODO: {line.strip()[:70]}")
        head = banner.replace("{name}", template.name)
        if args.dev:
            head += DEV_WARNING
        rendered[BUILD / template.name] = head + out

    if args.check:
        if problems:
            print("legal pack is NOT ready to publish:\n", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            print("\nSee docs/legal/README.md.", file=sys.stderr)
            return 1
        print(f"legal pack ready: {len(templates)} documents, nothing unfilled")
        return 0

    BUILD.mkdir(parents=True, exist_ok=True)
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
    print(f"rendered {len(rendered)} documents into {BUILD.relative_to(ROOT)}")
    if problems:
        print("\nstill to do before publishing:")
        for p in problems:
            print(f"  - {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
