#!/usr/bin/env python3
"""Render the legal templates against docs/legal/company.json.

One source of facts, several documents. Change a company detail once and every
document follows, which is the usual way legal pages quietly become untrue.

    python scripts/build_legal.py           # render into docs/legal/build/
    python scripts/build_legal.py --check   # exit non-zero if anything is unfilled

`--check` runs in the test suite, so a document still containing a TODO or an
unreplaced {{TOKEN}} cannot reach a website by accident.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEGAL = ROOT / "docs" / "legal"
TEMPLATES = LEGAL / "templates"
BUILD = LEGAL / "build"

TOKEN = re.compile(r"\{\{([A-Z0-9_]+)\}\}")

BANNER = """<!--
  GENERATED — do not edit this file.

  Source:   docs/legal/templates/{name}
  Values:   docs/legal/company.json
  Rebuild:  python scripts/build_legal.py

  DRAFT. Reviewed by counsel: NO. See docs/legal/README.md before publishing.
-->

"""


def load_values() -> dict[str, str]:
    raw = json.loads((LEGAL / "company.json").read_text(encoding="utf-8"))
    return {k: v for k, v in raw.items() if not k.startswith("_")}


def render(text: str, values: dict[str, str]) -> tuple[str, set[str]]:
    """Substitute tokens; report any the values file does not define."""
    missing: set[str] = set()

    def swap(match: re.Match) -> str:
        key = match.group(1)
        if key not in values:
            missing.add(key)
            return match.group(0)
        return str(values[key])

    return TOKEN.sub(swap, text), missing


def unfilled(values: dict[str, str]) -> list[str]:
    return sorted(k for k, v in values.items() if str(v).strip().startswith("TODO"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify everything is filled in; write nothing")
    args = parser.parse_args()

    values = load_values()
    templates = sorted(TEMPLATES.glob("*.md"))
    if not templates:
        print("no templates found", file=sys.stderr)
        return 1

    problems: list[str] = []
    todos = unfilled(values)
    if todos:
        problems.append(
            "company.json still has placeholders:\n"
            + "\n".join(f"    {k}" for k in todos)
        )

    rendered: dict[Path, str] = {}
    for template in templates:
        text = template.read_text(encoding="utf-8")
        out, missing = render(text, values)
        if missing:
            problems.append(
                f"{template.name} uses tokens company.json does not define: "
                + ", ".join(sorted(missing))
            )
        # a leftover TODO inside the prose itself
        for i, line in enumerate(out.split("\n"), 1):
            if "TODO" in line and not line.lstrip().startswith(">"):
                problems.append(f"{template.name}:{i} still says TODO: {line.strip()[:70]}")
        rendered[BUILD / template.name] = BANNER.format(name=template.name) + out

    if args.check:
        if problems:
            print("legal pack is NOT ready to publish:\n", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            print("\nSee docs/legal/README.md.", file=sys.stderr)
            return 1
        print(f"legal pack ready: {len(templates)} documents, nothing unfilled")
        return 0

    BUILD.mkdir(parents=True, exist_ok=True)
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
    print(f"rendered {len(rendered)} documents into {BUILD.relative_to(ROOT)}")
    if problems:
        print("\nstill to do before publishing:")
        for p in problems:
            print(f"  - {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
